services:
  - docker:dind

stages:
  # - test
  - build_publish

# sast:
#   stage: test

# include:
# - template: Security/SAST.gitlab-ci.yml

variables:
  CONTAINER_REGISTRY: hacknarog2022acr.azurecr.io

docker_build:
  stage: build_publish
  image: docker:latest
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $CONTAINER_REGISTRY
    - docker build -t $CONTAINER_REGISTRY/frontend:latest .
    - docker push $CONTAINER_REGISTRY/frontend:latest